[dosbox]
machine=cga
memsize=1

[render]
scaler=none

[cpu]
cputype=auto
cycles=3000

[serial]
serial1=nullmodem server port:5001

[dos]
hard drive data rate limit=0

[autoexec]
# Mount the project directory as C:
mount c /Users/jarrod/github/wordlelx
c:
cd output
WORDLDOS.EXE
