#!/usr/bin/env python3
"""Extract i812.com glyph table into static C assets for EXM renderer."""

from __future__ import annotations

import argparse
import pathlib
import struct
import sys

RECORD_SIZE = 18  # codepoint (u16) + 8 rows (u16 each)
FONT_HEIGHT = 8
FONT_WIDTH = 8


def u16(data: bytes, offset: int) -> int:
    return struct.unpack_from("<H", data, offset)[0]


def find_table_start(data: bytes) -> int:
    # The payload has a resident-string banner, then a 6-byte metadata block,
    # then fixed-size glyph records.
    marker = b"FCL font loader V1.03 resident\r\n$"
    pos = data.find(marker)
    search_start = 0x200 if pos < 0 else pos + len(marker)

    for off in range(search_start, min(search_start + 0x80, len(data) - RECORD_SIZE * 4)):
        c0 = u16(data, off)
        c1 = u16(data, off + RECORD_SIZE)
        c2 = u16(data, off + RECORD_SIZE * 2)
        c3 = u16(data, off + RECORD_SIZE * 3)
        if 0 < c0 < 0x100 and c0 < c1 < c2 < c3 < 0x100:
            return off

    raise ValueError("unable to locate i812 glyph table start")


def parse_glyphs(data: bytes, start: int) -> tuple[list[list[int]], list[int], int]:
    glyphs = [[0] * FONT_HEIGHT for _ in range(256)]
    present = [0] * 256
    offset = start
    prev = -1
    count = 0

    while offset + RECORD_SIZE <= len(data):
        code = u16(data, offset)
        if code == 0 or code > 0xFF:
            break
        if prev >= 0 and code <= prev:
            break

        rows = [u16(data, offset + 2 + row * 2) for row in range(FONT_HEIGHT)]
        glyphs[code] = rows
        present[code] = 1
        prev = code
        count += 1
        offset += RECORD_SIZE

    if count == 0:
        raise ValueError("no glyph records parsed")

    return glyphs, present, count


def emit_header(path: pathlib.Path) -> None:
    path.write_text(
        """/* Generated by extract_i812_font.py from i812.com. */
#ifndef I812_FONT_DATA_H
#define I812_FONT_DATA_H

#define I812_FONT_WIDTH 8
#define I812_FONT_HEIGHT 8

extern const unsigned short i812_font_glyphs[256][I812_FONT_HEIGHT];
extern const unsigned char i812_font_present[256];

#endif /* I812_FONT_DATA_H */
""",
        encoding="ascii",
    )


def emit_source(path: pathlib.Path, glyphs: list[list[int]], present: list[int]) -> None:
    lines: list[str] = []
    lines.append("/* Generated by extract_i812_font.py from i812.com. */")
    lines.append('#include "i812_font_data.h"')
    lines.append("")
    lines.append("const unsigned short i812_font_glyphs[256][I812_FONT_HEIGHT] = {")

    for code in range(256):
        rows = ", ".join(f"0x{row:04X}" for row in glyphs[code])
        lines.append(f"    /* 0x{code:02X} */ {{ {rows} }},")

    lines.append("};")
    lines.append("")
    lines.append("const unsigned char i812_font_present[256] = {")

    for base in range(0, 256, 16):
        chunk = ", ".join(str(v) for v in present[base : base + 16])
        lines.append(f"    /* 0x{base:02X} */ {chunk},")

    lines.append("};")
    lines.append("")

    path.write_text("\n".join(lines), encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=pathlib.Path, help="Path to i812.com")
    parser.add_argument("header", type=pathlib.Path, help="Output header path")
    parser.add_argument("source", type=pathlib.Path, help="Output C source path")
    args = parser.parse_args()

    data = args.input.read_bytes()
    start = find_table_start(data)
    glyphs, present, count = parse_glyphs(data, start)

    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.source.parent.mkdir(parents=True, exist_ok=True)

    emit_header(args.header)
    emit_source(args.source, glyphs, present)

    print(f"table_start=0x{start:04X}")
    print(f"glyph_count={count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
