[dosbox]
machine=cga
memsize=2

[render]
scaler=none

[cpu]
cputype=auto
cycles=5000

[dos]
hard drive data rate limit=0

[autoexec]
mount c /Users/jarrod/github/wordlelx
mount d /Users/jarrod/github/EXM
SET PATH=D:\TOOLS;%PATH%
c:
cd exm
E2M WORDLELX
exit
