/* Generated by extract_i812_font.py from i812.com. */
#ifndef I812_FONT_DATA_H
#define I812_FONT_DATA_H

#define I812_FONT_WIDTH 8
#define I812_FONT_HEIGHT 8

extern const unsigned short i812_font_glyphs[256][I812_FONT_HEIGHT];
extern const unsigned char i812_font_present[256];

#endif /* I812_FONT_DATA_H */
